# name: UIComponents
targets:
  UIComponents:
    templates: ['FrameworkTarget']
    dependencies:
      - target: 'Models'
    sources:
      - path: '../../Sources/UIComponents'
    # info:
    #   path: ../../Sources/UIComponents/Info.plist