name: GithubApp
fileGroups:
# - '../../.gitignore'
# - '../../Documents'
# - '../../README.md'
# - '../../LICENSE.md'
# - '../../Scripts'
#- '../../Templates'
# - '../../Configs/Cocoapods/Podfile'
# - '../../Configs/Cocoapods/Podfile.lock'
# - '../../Configs/Products'
# - '../../Configs/XcodeGen'
options:
  createIntermediateGroups: true
  developmentLanguage: 'ru'
  useBaseInternationalization: false
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  xcodeVersion: '${XCODEGEN_XCODE_VERSION}'
  groupSortPosition: top
  generateEmptyDirectories: true
settings:
  CURRENT_PROJECT_VERSION: '${XCODEGEN_BUILD_NUMBER}'
include:
# - common.yml
- path: ../GithubApp/targets/common.yml
  relativePaths: false
# - models.yml
- path: ../GithubApp/targets/modules/common/models.yml
  relativePaths: false
# - UIComponents.yml
- path: ../GithubApp/targets/modules/common/UIComponents.yml
  relativePaths: false
# - network.yml
- path: ../GithubApp/targets/modules/core/network.yml
  relativePaths: false
# - auth.yml
- path: ../GithubApp/targets/modules/flows/auth.yml
  relativePaths: false

targets:
  GithubApp:
    templates: [AppTarget]
    dependencies:
      - target: Authentication
  
