targetTemplates:
  templateApplication:
    templates: ['AppTarget']
    sources:
      - '../../Sources/Application'
targets:
  GithubApp:
    templates: ['templateApplication']
    dependencies:
    - target: 'NetworkFramework'
    - target: 'Authentication'