# name: Application
# targets:
#   Application:
#     templates: ['AppTarget']
#     dependencies:
#       - target: NetworkFramework
#     sources:
#       - path: '../../Sources/Application'

targetTemplates:
  templateApplication:
    templates: ['AppTarget']
    sources:
      - '../../Sources/Application'
targets:
  Application:
    templates: ['templateApplication']
    dependencies:
    - target: 'NetworkFramework'
    - target: 'Authentication'