project 'GithubApp.xcodeproj'
workspace 'GithubApp.xcworkspace'

platform :ios, '14.0'

target 'Application' do
  use_frameworks!

  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'Alamofire'
  pod 'SnapKit'

end

target 'Authentication' do
  use_frameworks!
  
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'Alamofire'
  pod 'SnapKit'
  
end

target 'NetworkFramework' do
  use_frameworks!
  
  pod 'Alamofire'

end
