platform :ios, '14.0'

project 'GithubApp.xcodeproj'
workspace 'GithubApp.xcworkspace'

target 'Application' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift', '6.5.0'
  pod 'Alamofire'
  pod 'SnapKit'

end
