name: GithubApp
fileGroups:
# - '../../.gitignore'
# - '../../Documents'
# - '../../README.md'
# - '../../LICENSE.md'
# - '../../Scripts'
#- '../../Templates'
# - '../../Configs/Cocoapods/Podfile'
# - '../../Configs/Cocoapods/Podfile.lock'
# - '../../Configs/Products'
# - '../../Configs/XcodeGen'
options:
  createIntermediateGroups: false
  developmentLanguage: 'ru'
  useBaseInternationalization: false
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  xcodeVersion: '5.7'
  groupSortPosition: top
  generateEmptyDirectories: true
settings:
  CURRENT_PROJECT_VERSION: '${XCODEGEN_BUILD_NUMBER}'
include:
- path: ../XcodeGen/common.yml
  relativePaths: false
- path: ../XcodeGen/targets/modules/common/models.yml
  relativePaths: false
- path: ../XcodeGen/targets/modules/common/UIComponents.yml
  relativePaths: false
- path: ../XcodeGen/targets/modules/core/network.yml
  relativePaths: false
- path: ../XcodeGen/targets/modules/flows/auth.yml
  relativePaths: false
- path: ../XcodeGen/targets/modules/Application/Application.yml
  relativePaths: false
  
